# Generated by Django 3.2.18 on 2023-03-05 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='floor_plan',
            field=models.ImageField(default='img/layout/strip-foundation.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='master_plan',
            field=models.ImageField(default='img/layout/strip-foundation.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tower_plan',
            field=models.ImageField(default='img/layout/strip-foundation.jpg', upload_to='media/'),
        ),
        migrations.CreateModel(
            name='FlatTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_types', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
            ],
        ),
    ]
